GET http://localhost:8080/api/articles
Accept: application/json
Cookie: JSESSIONID=2ADD254B485148E5FF510B0694A5CF63

###


###
POST http://localhost:8080/api/articles
Content-Type: application/json

{
  "authorId": 2,
  "content": "Spring MVC is easy content ...",
  "title": "Spring MVC is Easy"
}

###

