GET http://localhost:8080/api/posts
Accept: application/json

###
POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "title": "Swagger is Easy",
  "content": "Spring has good integration with swagger ...",
  "tags": [
    "spring",
    "swagger",
    "openapi"
  ]
}

###
DELETE http://localhost:8080/api/posts/5
Accept: application/json
