package org.iproduct.spring.restmvc.dao;

import lombok.extern.slf4j.Slf4j;
import org.iproduct.spring.restmvc.model.Article;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.PropertySource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import javax.annotation.PostConstruct;
import javax.sql.DataSource;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.ZonedDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Repository
@Slf4j
public class ArticleRepositoryImpl implements ArticleRepository {

    @Autowired
    private JdbcTemplate jdbcTemplate;

//    @Autowired
//    public void init(DataSource dataSource) {
//        jdbcTemplate = new JdbcTemplate(dataSource);
//    }

    @PostConstruct
    public void initDb() {
        log.info("Start data initialization  ...");
        jdbcTemplate.execute("DROP TABLE IF EXISTS articles");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS articles(" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "title VARCHAR(80), " +
                "content VARCHAR(512), " +
                "picture_url VARCHAR(128), " +
                "created TIMESTAMP, " +
                "updated TIMESTAMP" +
                ")");

        int articlesCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM articles", Integer.class);
        log.info("Articles count: {}", articlesCount);

        if (articlesCount == 0) {
            List<Article> articles = Arrays.asList(
                    new Article("Welcome to Spring 5", "Spring 5 is great beacuse ..."),
                    new Article("Dependency Injection", "Should I use DI or lookup ..."),
                    new Article("Spring Beans and Wireing", "There are several ways to configure Spring beans.")
            );

            // Use a Java 8 stream to print out each tuple of the list
            articles.forEach(article -> {
                log.info(String.format("Inserting article record for %s %s",
                        article.getTitle(), article.getContent()));
                jdbcTemplate.update("INSERT INTO articles(id, title, content, picture_url, created, updated) VALUES (DEFAULT, ?, ?, ?, ?, ?)",
                        article.getTitle(), article.getContent(), article.getPictureUrl(),
                        article.getCreated(),
                        article.getUpdated()
                        );
            });
        }

        log.info("Querying for article records where title contains = 'Spring':");
        jdbcTemplate.query(
            "SELECT id, title, content, picture_url, created, updated FROM articles WHERE title LIKE ?", new Object[]{"%Spring%"},
            (rs, rowNum) -> new Article(
                    rs.getLong("id"),
                    rs.getString("title"),
                    rs.getString("content"),
                    rs.getString("picture_url"),
                    rs.getTimestamp("created").toLocalDateTime(),
                    rs.getTimestamp("updated").toLocalDateTime())
        ).forEach(article -> log.info(article.toString()));
    }

    @Override
    public Collection<Article> findAll() {
        return null;
    }

    @Override
    public Optional<Article> findById(long id) {
        return Optional.empty();
    }

    @Override
    public Article insert(Article article) {
        return null;
    }

    @Override
    public Article save(Article article) {
        return null;
    }

    @Override
    public boolean deleteById(long articleId) {
        return false;
    }
}
