//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.27 at 02:12:39 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://iproduct.org/course/spring-web-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package course.spring.webservice.wsdl;
