package org.iproduct.spring.restmvc.dao;

import lombok.extern.slf4j.Slf4j;
import org.iproduct.spring.restmvc.model.Article;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.PropertySource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.PreparedStatementCreator;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import javax.annotation.PostConstruct;
import javax.sql.DataSource;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.ZonedDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Repository
@Slf4j
public class ArticleRepositoryImpl implements ArticleRepository {
    private static final String INSERT_SQL =
            "INSERT INTO articles(id, title, content, picture_url, created, updated) VALUES (DEFAULT, ?, ?, ?, ?, ?)";

    private JdbcTemplate jdbcTemplate;

    @Autowired
    public void init(DataSource dataSource) {
        jdbcTemplate = new JdbcTemplate(dataSource);
    }

    @Override
    public Collection<Article> findAll() {
        List<Article> articles = this.jdbcTemplate
                .query("select * from articles", new ArticleMapper());
        log.info("Articles loaded: {}", articles.size());
        return articles;
}

    @Override
    public Optional<Article> findById(long id) {
        Article article = this.jdbcTemplate.queryForObject(
                "select * from articles where id = ?",
                new Object[]{id}, new ArticleMapper());
        log.info("Article found: {}", article);
        return Optional.of(article);
    }

    @Override
    @Transactional
    public Article insert(Article article) {
        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbcTemplate.update(new PreparedStatementCreator() {
            public PreparedStatement createPreparedStatement(Connection connection) throws SQLException {
                PreparedStatement ps = connection.prepareStatement(INSERT_SQL, new String[] {"id"});
                ps.setString(1, article.getTitle());
                ps.setString(2, article.getContent());
                ps.setString(3, article.getPictureUrl());
                ps.setTimestamp(4, new Timestamp(article.getCreated().toInstant(ZoneOffset.UTC).toEpochMilli()));
                ps.setTimestamp(5, new Timestamp(article.getCreated().toInstant(ZoneOffset.UTC).toEpochMilli()));

                return ps;
            }
        }, keyHolder);
        article.setId(keyHolder.getKey().longValue());
        log.info("Article created: {}", article);
        return article;
    }


    @Override
    public Article save(Article article) {
        int count = this.jdbcTemplate.update(
            "update articles set (title, content, picture_url, created, updated) = (?, ?, ?, ?, ?) where id = ?",
            article.getTitle(), article.getContent(), article.getPictureUrl(),
            article.getCreated(),
            article.getUpdated(),
            article.getId());
        log.info("Article updated: {}", article);
        return article;
    }

    @Override
    public boolean deleteById(long articleId) {
        int count = this.jdbcTemplate.update(
                "delete from articles where id = ?",
                Long.valueOf(articleId));
        return count > 0;
    }

    @PostConstruct
    public void initDb() {
        log.info("Start data initialization  ...");
//        jdbcTemplate.execute("DROP TABLE IF EXISTS articles");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS articles(" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "title VARCHAR(80), " +
                "content VARCHAR(512), " +
                "picture_url VARCHAR(128), " +
                "created TIMESTAMP, " +
                "updated TIMESTAMP" +
                ")");

        int articlesCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM articles", Integer.class);
        log.info("Articles count: {}", articlesCount);

        if (articlesCount == 0) {
            List<Article> articles = Arrays.asList(
                    new Article("Welcome to Spring 5", "Spring 5 is great beacuse ..."),
                    new Article("Dependency Injection", "Should I use DI or lookup ..."),
                    new Article("Spring Beans and Wireing", "There are several ways to configure Spring beans.")
            ).stream().collect(Collectors.toList());

            // Use a Java 8 stream to print out each tuple of the list
            articles.forEach(article -> {
                log.info(String.format("Inserting article record for %s %s",
                        article.getTitle(), article.getContent()));
                jdbcTemplate.update("INSERT INTO articles(id, title, content, picture_url, created, updated) VALUES (DEFAULT, ?, ?, ?, ?, ?)",
                        article.getTitle(), article.getContent(), article.getPictureUrl(),
                        article.getCreated(),
                        article.getUpdated()
                );
            });
        }

        log.info("Querying for article records where title contains = 'Spring':");
        jdbcTemplate.query(
                "SELECT id, title, content, picture_url, created, updated FROM articles WHERE title LIKE ?", new Object[]{"%Spring%"},
                (rs, rowNum) -> new Article(
                        rs.getLong("id"),
                        rs.getString("title"),
                        rs.getString("content"),
                        rs.getString("picture_url"),
                        rs.getTimestamp("created").toLocalDateTime(),
                        rs.getTimestamp("updated").toLocalDateTime())
        ).forEach(article -> log.info(article.toString()));
    }

    private static final class ArticleMapper implements RowMapper<Article> {
        public Article mapRow(ResultSet rs, int rowNum) throws SQLException {
            return new Article(
                    rs.getLong("id"),
                    rs.getString("title"),
                    rs.getString("content"),
                    rs.getString("picture_url"),
                    rs.getTimestamp("created").toLocalDateTime(),
                    rs.getTimestamp("updated").toLocalDateTime());
        }
    }
}
