//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.20 at 11:30:36 AM EEST 
//
@XmlSchema(
        namespace = "http://iproduct.org/course/spring-web-service",
        elementFormDefault = XmlNsForm.QUALIFIED,
        xmlns = {
                @XmlNs(prefix="cs", namespaceURI="http://iproduct.org/course/spring-web-service")
        }
)
package course.spring.webservice.wsdl;
import javax.xml.bind.annotation.*;
