server:
  application:
    name: REST MVC Demo
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hibernate_books2?createDatabaseIfNotExist=true
    username: root
    password: root
  #JPA Properties
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        generate_statistics: true
        metadata_builder_contributor: course.hibernate.spring.config.CustomMetadataBuilderContributor
        cache:
          use_second_level_cache: true
          default_cache_concurrency_strategy: read-write
          use_query_cache: true
          region:
            factory_class: jcache
        jakarta:
          cache:
            uri: classpath:ehcache.xml

#        bytecode:
#          allow_enhancement_as_proxy: true
#          use_reflection_optimizer: true
#          provider: org.hibernate.bytecode.internal.javassist.BytecodeProviderImpl
#        enhancer:
#          enableDirtyTracking: true
#          enableLazyInitialization: true
#          enableAssociationManagement: true

    hibernate:
      ddl-auto: create
    open-in-view: false

#    mongodb:
#      host: localhost
#      port: 27017
#      database: articles_spring_2021

management:
  endpoints:
    web:
      exposure:
        include: info, health, mappings, metrics, threaddump, heapdump, shutdown, beans, logfile, loggers
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
      cache:
        time-to-live: -1
  info:
    defaults:
      enabled: true
    java:
      enabled: true
    build:
      enabled: true
    env:
      enabled: true
info:
  app:
    encoding: "UTF-8"
    name: REST MVC Demo
    description: REST MVC demo with Spring Boot and Spring Data JPA
    version: 1.0-SNAPSHOT
logging:
  level:
    root: INFO
    org:
      springframework:
        test:
          context:
            support: INFO
      hibernate:
        type: trace
        stat: debug
    course:
      hibernate:
        spring: debug
blog:
  api:
    prefix: /api/v2

jwt:
  secret: ${JWT_SECRET:not_a_secret}

