package course.spring.webmvc.init;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.jdbc.core.JdbcTemplate;

public class DataInitializer  implements ApplicationRunner {
    public static final String DROP_ARTICLES_TABLE = "DROP TABLE IF EXISTS articles2";
    public static final String CREATE_ARTICLES_TABLE =
            "CREATE TABLE IF NOT EXISTS articles2(" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "title VARCHAR(80), " +
                    "content VARCHAR(512), " +
                    "created_date TIMESTAMP, " +
                    "picture_url VARCHAR(80)" +
                    ")";
    public static final String DROP_USERS_TABLE = "DROP TABLE IF EXISTS users2";
    public static final String CREATE_USERS_TABLE =
           "CREATE TABLE IF NOT EXISTS users2(" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "username VARCHAR(40), " +
                    "password VARCHAR(80), " +
                    "fname VARCHAR(40), " +
                    "lname VARCHAR(40), " +
                    "roles VARCHAR(80), " +
                    "active BOOLEAN, " +
                    "created TIMESTAMP, " +
                    "updated TIMESTAMP" +
                    ")";

    @Autowired
    private JdbcTemplate jdbcTemplate;
    @Override
    public void run(ApplicationArguments args) throws Exception {

    }
}
